site_name: Differentially Private Voice Control

theme:
  name: "material"
  features:
    - content.code.copy

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - using.md
  - training.md
  - wrapping.md
  - reference.md